/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircuitsRouteImport } from './routes/circuits'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NewsRouteImport } from './routes/news'
import { Route as RacesRouteImport } from './routes/races'
import { Route as SeasonRouteImport } from './routes/season'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as DriversDriverIdRouteImport } from './routes/drivers.$driverId'
import { Route as RaceRaceIdRouteImport } from './routes/race.$raceId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitsRoute = CircuitsRouteImport.update({
  id: '/circuits',
  path: '/circuits',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const RacesRoute = RacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonRoute = SeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DriversDriverIdRoute = DriversDriverIdRouteImport.update({
  id: '/$driverId',
  path: '/$driverId',
  getParentRoute: () => DriversRoute,
} as any)
const RaceRaceIdRoute = RaceRaceIdRouteImport.update({
  id: '/race/$raceId',
  path: '/race/$raceId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/compare': typeof CompareRoute
  '/drivers': typeof DriversRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/races': typeof RacesRoute
  '/season': typeof SeasonRoute
  '/strategy': typeof StrategyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/compare': typeof CompareRoute
  '/drivers': typeof DriversRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/races': typeof RacesRoute
  '/season': typeof SeasonRoute
  '/strategy': typeof StrategyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circuits': typeof CircuitsRoute
  '/compare': typeof CompareRoute
  '/drivers': typeof DriversRouteWithChildren
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/races': typeof RacesRoute
  '/season': typeof SeasonRoute
  '/strategy': typeof StrategyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/race/$raceId': typeof RaceRaceIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circuits'
    | '/compare'
    | '/drivers'
    | '/mcp'
    | '/news'
    | '/races'
    | '/season'
    | '/strategy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/drivers/$driverId'
    | '/race/$raceId'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circuits'
    | '/compare'
    | '/drivers'
    | '/mcp'
    | '/news'
    | '/races'
    | '/season'
    | '/strategy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/drivers/$driverId'
    | '/race/$raceId'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/circuits'
    | '/compare'
    | '/drivers'
    | '/mcp'
    | '/news'
    | '/races'
    | '/season'
    | '/strategy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/drivers/$driverId'
    | '/race/$raceId'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircuitsRoute: typeof CircuitsRoute
  CompareRoute: typeof CompareRoute
  DriversRoute: typeof DriversRouteWithChildren
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  RacesRoute: typeof RacesRoute
  SeasonRoute: typeof SeasonRoute
  StrategyRoute: typeof StrategyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  RaceRaceIdRoute: typeof RaceRaceIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuits': {
      id: '/circuits'
      path: '/circuits'
      fullPath: '/circuits'
      preLoaderRoute: typeof CircuitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/races': {
      id: '/races'
      path: '/races'
      fullPath: '/races'
      preLoaderRoute: typeof RacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season': {
      id: '/season'
      path: '/season'
      fullPath: '/season'
      preLoaderRoute: typeof SeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/$driverId': {
      id: '/drivers/$driverId'
      path: '/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof DriversDriverIdRouteImport
      parentRoute: typeof DriversRoute
    }
    '/race/$raceId': {
      id: '/race/$raceId'
      path: '/race/$raceId'
      fullPath: '/race/$raceId'
      preLoaderRoute: typeof RaceRaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DriversRouteChildren {
  DriversDriverIdRoute: typeof DriversDriverIdRoute
}

const DriversRouteChildren: DriversRouteChildren = {
  DriversDriverIdRoute: DriversDriverIdRoute,
}

const DriversRouteWithChildren =
  DriversRoute._addFileChildren(DriversRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircuitsRoute: CircuitsRoute,
  CompareRoute: CompareRoute,
  DriversRoute: DriversRouteWithChildren,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  RacesRoute: RacesRoute,
  SeasonRoute: SeasonRoute,
  StrategyRoute: StrategyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  RaceRaceIdRoute: RaceRaceIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
